export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const FETCH_REQUEST = "FETCH_REQUEST";
export const FETCH_REQUEST_SUCCESS = "FETCH_REQUEST_SUCCESS";
export const FETCH_REQUEST_FAILURE = "FETCH_REQUEST_FAILURE";
